### ISSUE TITLE
OSCTestSender Problem

### ISSUE THREAD

**Issue by CaroRed** [robertoranon/OSC-Unity5#1]
Hey I'm using your package and I found it very simple to use but i'm having problems with OSCTestSender.cs script. the error I got is 

> NullReferenceException: Object reference not set to an instance of an object
OSCTestSender.Update () (at Assets/Scripts/OSCTestSender.cs:37)

That part of the code is:

` OscMessage oscM = Osc.StringToOscMessage("/1/push1");
        oscHandler.Send(oscM);`

Can you help me to see what is wrong.

Thank you so much for your work.

**Comment by robertoranon** [comment]
Hello!
If you didn't change anything in the code, the error might be related to the fact that you don't have any OSC message with the address "/1/push1". In other words, you need your OSC sending application to send a message with that address, or change that string ("/1/push1") to the address string that your application is sending.

**Comment by CaroRed** [comment]
No I got the address "/1/push1" on the receiver and it works cause I tested it from a web browser with php. The problem is in Unity. Could it be the problem in this part:

`  void Start()
    {

        UDPPacketIO udp = GetComponent<UDPPacketIO>();
        udp.init(remoteIp, sendToPort, listenerPort);

	    oscHandler = GetComponent<Osc>();
        oscHandler.init(udp);

        oscHandler.SetAddressHandler("/hand1", Example);
    }
`
This "oscHandler.SetAddressHandler("/hand1", Example);" Needs to be declare on my receiver app?

Thank you.

**Comment by robertoranon** [comment]
That script (OSCTestSender.cs) is for sending OSC events, not receiving them into Unity. Do you need to send OSC events out of Unity?

**Comment by CaroRed** [comment]
I need to create two app for unity, one is going to be the listener in a desktop, and the other will be the sender from a tablet device.

**Comment by robertoranon** [comment]
I never tried to send OSC events out of Unity - I think that file was just a leftover from an initial code that I found on Unity forums. I might have some time to see why it doesn't work, but I cannot guarantee  when, sorry. It will help tough if you could send me a minimal Unity project with the problem.

**Comment by robertoranon** [comment]
I've committed a couple of changes to OSCTestSender.cs that remove the errors you were experiencing. I still don't know, however, if you can actually send events. If you want to give it a try...
